//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace alo_alo.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class AdminUser
    {
        [Display(Name ="Mã User")]
        [Required(ErrorMessage = "Mã User không được để trống ..")]
        public int ID { get; set; }

        [Display(Name = "Tên User")]
        public string NameUser { get; set; }

        [Display(Name = "Vai trò")]
        public string RoleUser { get; set; }

        [Display(Name ="Nhập Mật Khẩu")]
        [Required(ErrorMessage = "Mật khẩu không được để trống ..")]
        [DataType(DataType.Password)]
        public string PasswordUser { get; set; }


        [NotMapped]
        [Compare("PasswordUser", ErrorMessage = "Nhập lại mật khẩu không khớp !!")]
        [DisplayName("Nhập lại mật khẩu")]
        [DataType(DataType.Password)]
        public string ConfirmPass { get; set; }
        [NotMapped]
        public string ErrorLogin { get;set; }
    }
}
