//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System.ComponentModel.DataAnnotations;

namespace alo_alo.Models
{
    using System;
    using System.Collections.Generic;
    using Xunit;

    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.OrderDetails = new HashSet<OrderDetail>();
        }

        [Required(ErrorMessage = "Tên sp để thuộc công ty của Dương Mộng Gà")]
        public int ProductID { get; set; }

        [Required(ErrorMessage = "Tên sp để thuộc công ty của Dương Mộng Gà")]
        public string NamePro { get; set; }
        [Required(ErrorMessage = "Tên sp để thuộc công ty của Dương Mộng Gà")]
        public string DecriptionPro { get; set; }
        public string Category { get; set; }
        
        [RegularExpression("^\\d{0,8}(\\.\\d{1,4})?$", ErrorMessage ="Phải thoả mảng đủ tiền Của Dương mộng gà")]
        //1.      Maximum 8 digits before decimal (.) point
        //2.      Maximum 4 digits after decimal point
        //3.      Decimal point is optional
        public Nullable<decimal> Price { get; set; }
        public string ImagePro { get; set; }
    
        public virtual Category Category1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderDetail> OrderDetails { get; set; }
    }
}
